FROM python:3.13.12

WORKDIR /app

#Req.txt
COPY requirements.txt /app/requirements.txt

#Pip install requirements.

RUN pip install --no-cache-dir -r /app/requirements.txt

COPY frontend /app/frontend

ENV PORT=8080
EXPOSE 8080

CMD ["streamlit", "run", "frontend/app.py", "--server.address=0.0.0.0", "--server.port=8080"]